import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, Heart, Scissors, Sparkles } from "lucide-react";
import brideImage from "../assets/oz-bride-editorial.jpg";
import bridesmaidsImage from "../assets/oz-bridesmaids-editorial.jpg";

export const Route = createFileRoute("/about")({ head: () => ({ meta: [
  { title: "About OZ Fashion House | Namugongo Bridal Boutique" }, { name: "description", content: "Meet OZ Fashion House, a bridal clothing and accessories business serving couples and wedding parties in Namugongo, Wakiso." },
  { property: "og:title", content: "About OZ Fashion House" }, { property: "og:description", content: "Wedding style thoughtfully brought together in Namugongo, Wakiso." },
  { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
] }), component: AboutPage });

function AboutPage() { return <main><section className="page-intro"><div className="page-intro-inner"><p className="eyebrow">About OZ Fashion House</p><h1 className="page-title">Beautifully dressed.<br/>Thoughtfully remembered.</h1><p className="page-lead">We bring the complete wedding wardrobe together in Namugongo—from the bride and groom to bridesmaids and every finishing accessory.</p></div></section><section className="px-5 py-20 sm:px-8 sm:py-28 lg:px-12"><div className="mx-auto grid max-w-screen-2xl gap-12 lg:grid-cols-2 lg:items-center lg:gap-24"><img src={brideImage} alt="OZ Fashion House bridal gown" width={1200} height={1504} className="aspect-[4/5] w-full object-cover"/><div><p className="eyebrow">Our point of view</p><h2 className="section-title">The day is yours.<br/>The details are ours.</h2><p className="mt-7 font-sans text-base leading-8 text-muted-foreground">OZ Fashion House exists to make wedding dressing feel considered, coordinated and personal. We help couples and their wedding parties discover outfits and accessories that feel right for the celebration they are creating.</p><p className="mt-5 font-sans text-base leading-8 text-muted-foreground">Based in Namugongo, Wakiso, our collection brings together refined bridal silhouettes, confident groom styling, harmonious bridesmaid looks and thoughtful finishing pieces for women and men.</p></div></div></section><section className="bg-secondary px-5 py-20 sm:px-8 lg:px-12"><div className="mx-auto max-w-screen-2xl"><div className="grid gap-8 md:grid-cols-3">{[[Heart,"Personal attention","Your vision leads every recommendation."],[Scissors,"Complete styling","Looks for the entire wedding party, brought together."],[Sparkles,"Finishing detail","Accessories chosen to make every outfit feel complete."]].map(([Icon,title,copy]) => { const I=Icon as typeof Heart; return <article key={title as string} className="border-t border-primary pt-6"><I className="size-6 text-primary"/><h3 className="mt-8 font-display text-3xl">{title as string}</h3><p className="mt-4 font-sans text-sm leading-7 text-muted-foreground">{copy as string}</p></article>})}</div></div></section><section className="px-5 py-20 sm:px-8 sm:py-28 lg:px-12"><div className="mx-auto grid max-w-screen-2xl gap-12 lg:grid-cols-[1fr_1.2fr] lg:items-center"><div><p className="eyebrow">Together in style</p><h2 className="section-title">A celebration looks best when it feels connected.</h2><Link to="/collections" className="mt-8 inline-flex min-h-14 items-center gap-3 bg-primary px-6 font-sans text-xs font-bold uppercase tracking-[0.15em] text-primary-foreground">Explore collections <ArrowRight className="size-4"/></Link></div><img src={bridesmaidsImage} alt="Coordinated bridesmaid dresses" loading="lazy" width={1200} height={1504} className="aspect-[16/10] w-full object-cover"/></div></section></main> }