import { createFileRoute, Link } from "@tanstack/react-router";
import { Clock, MapPin, MessageCircle, Phone } from "lucide-react";
import { whatsappNumber } from "../lib/catalog";

export const Route = createFileRoute("/contact")({ head: () => ({ meta: [
  { title: "Contact OZ Fashion House | Namugongo, Wakiso" }, { name: "description", content: "Contact OZ Fashion House in Namugongo, Wakiso on WhatsApp for bridal wear, groom suits, bridesmaid dresses and accessories." },
  { property: "og:title", content: "Contact OZ Fashion House" }, { property: "og:description", content: "Plan your visit or speak with OZ Fashion House on WhatsApp." },
  { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
] }), component: ContactPage });

function ContactPage() { const message=encodeURIComponent("Hello OZ Fashion House, I would like to plan a visit and enquire about your wedding collection."); return <main><section className="page-intro"><div className="page-intro-inner"><p className="eyebrow">We would love to hear from you</p><h1 className="page-title">Plan your visit</h1><p className="page-lead">Tell us what you are looking for and we will help you find the right wedding look for you and your party.</p></div></section><section className="px-5 py-20 sm:px-8 sm:py-28 lg:px-12"><div className="mx-auto grid max-w-screen-xl gap-8 lg:grid-cols-[1.1fr_0.9fr]"><div className="bg-secondary p-7 sm:p-12"><p className="eyebrow">Start the conversation</p><h2 className="mt-4 font-display text-4xl sm:text-5xl">Chat directly with our team.</h2><p className="mt-5 max-w-xl font-sans text-sm leading-7 text-muted-foreground">WhatsApp is the quickest way to ask about availability, fittings, group styling and accessories. Include your wedding date and the pieces you are interested in.</p><a href={`https://wa.me/${whatsappNumber}?text=${message}`} target="_blank" rel="noreferrer" className="mt-8 inline-flex min-h-14 items-center gap-3 bg-primary px-6 font-sans text-xs font-bold uppercase tracking-[0.15em] text-primary-foreground"><MessageCircle className="size-5"/> Message on WhatsApp</a></div><div className="border border-border p-7 sm:p-12"><h2 className="font-display text-4xl">Visit & contact</h2><div className="mt-8 space-y-7 font-sans text-sm"><div className="flex gap-4"><MapPin className="size-5 shrink-0 text-primary"/><div><p className="font-semibold">Location</p><p className="mt-1 text-muted-foreground">Namugongo, Wakiso, Uganda</p></div></div><div className="flex gap-4"><Phone className="size-5 shrink-0 text-primary"/><div><p className="font-semibold">Telephone</p><a href="tel:+256701090109" className="mt-1 block text-muted-foreground">+256 701 090 109</a></div></div><div className="flex gap-4"><Clock className="size-5 shrink-0 text-primary"/><div><p className="font-semibold">Appointments</p><p className="mt-1 text-muted-foreground">Contact us on WhatsApp to arrange your visit.</p></div></div></div></div></div><div className="mx-auto mt-16 max-w-screen-xl border-t border-border pt-10 text-center"><h2 className="font-display text-3xl">Already know what you love?</h2><Link to="/collections" className="mt-5 text-link">Browse the shop</Link></div></section></main> }